draw_config:
  dark_mode: true
  key_w: 64.0
  key_h: 56.0
  key_rx: 8.0
  key_ry: 8.0
  split_gap: 40.0
  combo_w: 28.0
  combo_h: 20.0
  n_columns: 12
  key_font_size: 12.0
  legend_font_size: 11.0
  small_text: 9.0
  svg_style: |
    .keymap-key {
      filter: drop-shadow(0 2px 3px rgba(0,0,0,0.4));
    }
    
    .combo {
      opacity: 0.9;
    }
    
    .held {
      fill: #64748b !important;
    }
    
    .tap {
      fill: #334155 !important;
      color: #f1f5f9 !important;
    }
    
    .legend {
      font-weight: 500;
    }
  separate_combo_diagrams: true
  shrink_wide_legends: 8.0
  glyph_tap_size: 14.0
  glyph_hold_size: 12.0
  append_colon_to_layer_header: false

parse_config:
  preprocess: true
  sticky_label: "sticky"
  toggle_label: "toggle"
  trans_legend:
    type: "trans"
    tap: "▽"
    align: "center"
  
  # Define layer names to match your keymap
  layer_names:
    0: "Default"
    1: "Farrows"
    2: "Symbols"
    3: "Gaming"
    4: "Bluetooth"
  
  # Parse mod-tap behaviors properly
  zmk_combos:
    # This ensures combos are parsed correctly
    parse: true
  
  # Define how to parse ZMK behaviors
  zmk_behaviors:
    "&mt":
      type: "mod_tap"
      parse_fn: "zmk_mod_tap"
    "&gresc":
      type: "mod_tap"
      tap: "ESC"
      hold: "GRAVE"
    "&tog":
      type: "layer_toggle"
    "&mo":
      type: "momentary_layer"
    "&bootloader":
      type: "bootloader"
      tap: "BOOT"
  
  # Mod-tap parsing for home row mods
  mod_tap_labels:
    LEFT_WIN: "GUI"
    RIGHT_WIN: "GUI"
    LEFT_ALT: "ALT"
    RIGHT_ALT: "ALT"
    LEFT_SHIFT: "SHFT"
    RIGHT_SHIFT: "SHFT"
    LCTRL: "CTRL"
    RCTRL: "CTRL"
  
  zmk_keycode_map:
    GRAVE: "`"
    TILDE: "~"
    SPACE: "SPC"
    TAB: "TAB"
    RET: "ENTER" 
    ENTER: "ENTER"
    ESC: "ESC"
    BSPC: "BKSP"
    BACKSPACE: "BKSP"
    DEL: "DEL"
    LSHFT: "SHFT"
    RSHFT: "SHFT" 
    LCTRL: "CTRL"
    RCTRL: "CTRL"
    LALT: "ALT"
    RALT: "ALT"
    LGUI: "GUI"
    RGUI: "GUI"
    LEFT_WIN: "WIN"
    RIGHT_WIN: "WIN"
    LEFT: "←"
    RIGHT: "→" 
    UP: "↑"
    DOWN: "↓"
    MINUS: "-"
    EQUAL: "="
    PLUS: "+"
    UNDERSCORE: "_"
    PIPE: "|"
    BACKSLASH: "\\"
    NON_US_BACKSLASH: "\\"
    SEMICOLON: ";"
    SQT: "'"
    DOUBLE_QUOTES: "\""
    COMMA: ","
    DOT: "."
    FSLH: "/"
    LBKT: "["
    RBKT: "]"
    LPAR: "("
    RPAR: ")"
    LBRC: "{"
    RBRC: "}"
    LT: "<"
    GT: ">"
    PG_UP: "PGUP"
    PG_DN: "PGDN"
    HOME: "HOME"
    END: "END"
    INSERT: "INS"
    PRINTSCREEN: "PRNT"
    F1: "F1"
    F2: "F2" 
    F3: "F3"
    F4: "F4"
    F5: "F5"
    F6: "F6"
    F7: "F7"
    F8: "F8"
    F9: "F9"
    F10: "F10"
    F11: "F11"
    F12: "F12"
    # Bluetooth keycodes
    BT_SEL: "BT"
    BT_CLR: "BTCLR"
    BT_NXT: "BT+"
    BT_PRV: "BT-"
    # Special keycodes
    LC: "L⌃"
    LS: "L⇧"
    DOLLAR: "$"
