draw_config:
  dark_mode: false
  key_w: 60.0
  key_h: 54.0
  key_rx: 6.0
  key_ry: 6.0
  split_gap: 30.0
  combo_w: 26.0
  combo_h: 22.0
  n_columns: 12
  key_font_size: 12.0
  legend_font_size: 10.0
  small_text: 9.0
  svg_style: |
    .keymap {
      font-family: "SF Pro Text", Inter, system-ui, -apple-system, sans-serif;
      font-weight: 400;
      background: #ffffff;
    }
    rect.key {
      fill: #f8fafc;
      stroke: #e2e8f0;
      stroke-width: 1;
      rx: 6;
    }
    
    text {
      fill: #0f172a;
    }
    
    text.tap {
      font-size: 13px;
      font-weight: 500;
      fill: #0f172a;
    }
    
    text.hold {
      font-size: 10px;
      font-weight: 400;
      fill: #3b82f6;
    }
    
    text.shifted {
      font-size: 10px;
      fill: #7c3aed;
    }
    
    text.label {
      font-size: 16px;
      font-weight: 600;
      fill: #0f172a;
    }
    
    .layer-activator {
      fill: #059669;
      font-weight: 500;
      text-decoration: none;
    }
    
    rect.held {
      fill: #fef3c7;
      stroke: #fbbf24;
      stroke-width: 2;
    }
    
    rect.combo {
      fill: #dbeafe;
      stroke: #3b82f6;
      stroke-width: 1;
    }
    
    .combo text {
      font-size: 10px;
      fill: #1e40af;
    }
    
    rect.ghost {
      stroke-dasharray: 3, 2;
      stroke-width: 1;
      opacity: 0.5;
    }
    
    .trans {
      opacity: 0.3;
    }

    text.key tspan {
      font-size: 10px;
    }
    

    path.combo {
      stroke: #cbd5e1;
      stroke-width: 1;
    }
    

    text.footer {
      font-size: 11px;
      fill: #64748b;
    }
  
  # Layout settings
  separate_combo_diagrams: false
  shrink_wide_legends: 7.0
  glyph_tap_size: 13.0
  glyph_hold_size: 10.0
  glyph_shifted_size: 10.0
  append_colon_to_layer_header: false
  
  # Spacing
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  line_spacing: 1.2
  
  # Footer
  footer_text: "Created with keymap-drawer"
  
  # Output settings
  use_text_path: false

parse_config:
  zmk_version: 0.1
  preprocess: true
  
  layer_names:
    "0": "Base"
    "1": "Arrows" 
    "2": "Symbols"
    "3": "Gaming"
    "4": "Bluetooth"
  
  sticky_label: "sticky"
  toggle_label: "tog"
  trans_legend:
    tap: "▽"
    type: "trans"
  
  raw_binding_map:
    # Mod-tap home row mods
    "&mt LEFT_WIN A": { t: "A", h: "GUI" }
    "&mt LEFT_ALT S": { t: "S", h: "ALT" }
    "&mt LEFT_SHIFT D": { t: "D", h: "SFT" }
    "&mt LCTRL F": { t: "F", h: "CTL" }
    "&mt RCTRL J": { t: "J", h: "CTL" }
    "&mt RIGHT_SHIFT K": { t: "K", h: "SFT" }
    "&mt RIGHT_ALT L": { t: "L", h: "ALT" }
    "&mt LEFT_WIN SEMICOLON": { t: ";", h: "GUI" }
    "&mt LEFT_WIN SEMI": { t: ";", h: "GUI" }
    # Other mod-taps
    "&mt LEFT_GUI LESS_THAN": { t: "<", h: "GUI" }
    "&mt LEFT_ALT GREATER_THAN": { t: ">", h: "ALT" }
    "&mt LEFT_SHIFT LBRC": { t: "{", h: "SFT" }
    "&mt LCTRL RBRC": { t: "}", h: "CTL" }
    "&mt LEFT_WIN F6": { t: "F6", h: "GUI" }
    "&mt LEFT_ALT F7": { t: "F7", h: "ALT" }
    "&mt LEFT_SHIFT F8": { t: "F8", h: "SFT" }
    "&mt LCTRL F9": { t: "F9", h: "CTL" }
    # Special behaviors
    "&gresc": { t: "ESC", s: "`" }
    "&bootloader": "BOOT"
    # Layer keys
    "&mo 1": { t: "Lower", type: "held" }
    "&mo 2": { t: "Raise", type: "held" }
    "&tog 3": { t: "Gaming", type: "toggle" }
    "&tog 4": { t: "BT", type: "toggle" }
    # Bluetooth
    "&bt BT_SEL 0": "BT0"
    "&bt BT_SEL 1": "BT1" 
    "&bt BT_SEL 2": "BT2"
    "&bt BT_SEL 3": "BT3"
    "&bt BT_SEL 4": "BT4"
    "&bt BT_CLR": "BTCLR"
    "&bt BT_NXT": "BT+"
    "&bt BT_PRV": "BT-"
  
  # Clean, minimal keycodes
  zmk_keycode_map:
    # Letters stay as is
    # Numbers stay as is
    
    # Modifiers - minimal
    LCTRL: "⌃"
    RCTRL: "⌃"
    LALT: "⌥"
    RALT: "⌥"
    LGUI: "⌘"
    RGUI: "⌘"
    LSHFT: "⇧"
    RSHFT: "⇧"
    LEFT_CONTROL: "CTRL"
    RIGHT_CONTROL: "CTRL"
    LEFT_ALT: "ALT"
    RIGHT_ALT: "ALT"
    LEFT_SHIFT: "SHIFT"
    RIGHT_SHIFT: "SHIFT"
    LEFT_WIN: "GUI"
    RIGHT_WIN: "GUI"
    
    # Navigation
    LEFT: "←"
    RIGHT: "→"
    UP: "↑"
    DOWN: "↓"
    HOME: "⇱"
    END: "⇲"
    PG_UP: "⇞"
    PG_DN: "⇟"
    
    # Common keys
    SPACE: "⎵"
    TAB: "⇥"
    RET: "⏎"
    ENTER: "⏎"
    ESC: "⎋"
    BSPC: "⌫"
    DEL: "⌦"
    
    # Symbols
    GRAVE: "`"
    MINUS: "-"
    EQUAL: "="
    LBKT: "["
    RBKT: "]"
    BSLH: "\\"
    SEMI: ";"
    SEMICOLON: ";"
    SQT: "'"
    COMMA: ","
    DOT: "."
    FSLH: "/"
    
    # Shifted symbols
    TILDE: "~"
    EXCL: "!"
    AT: "@"
    HASH: "#"
    DOLLAR: "$"
    PRCNT: "%"
    CARET: "^"
    AMPS: "&"
    STAR: "*"
    LPAR: "("
    RPAR: ")"
    UNDER: "_"
    PLUS: "+"
    LBRC: "{"
    RBRC: "}"
    PIPE: "|"
    COLON: ":"
    DQT: '"'
    DOUBLE_QUOTES: '"'
    LT: "<"
    GT: ">"
    LESS_THAN: "<"
    GREATER_THAN: ">"
    QMARK: "?"
    
    # Function keys
    F1: "F1"
    F2: "F2"
    F3: "F3"
    F4: "F4"
    F5: "F5"
    F6: "F6"
    F7: "F7"
    F8: "F8"
    F9: "F9"
    F10: "F10"
    F11: "F11"
    F12: "F12"
    
    # Special keys
    INSERT: "INS"
    PRINTSCREEN: "PRNT"
    CAPS: "CAPS"
    
    # Lock
    SLCK: "SCRL"
    NLCK: "NUM"
    
    # Short versions for long names
    BACKSPACE: "BKSP"
    SLASH: "/"
    BACKSLASH: "\\"
    LEFT_BRACKET: "["
    RIGHT_BRACKET: "]"
    UNDERSCORE: "_"
    NON_US_BACKSLASH: "\\"
    
  # Combo configuration
  zmk_combos:
    enabled: true
