draw_config:
  dark_mode: true
  key_w: 64.0
  key_h: 56.0
  key_rx: 8.0
  key_ry: 8.0
  split_gap: 40.0
  combo_w: 28.0
  combo_h: 20.0
  n_columns: 12
  key_font_size: 12.0
  legend_font_size: 11.0
  small_text: 9.0
  svg_style: |
    .keymap-key {
      filter: drop-shadow(0 2px 3px rgba(0,0,0,0.4));
    }
    
    .combo {
      opacity: 0.9;
    }
    
    .held {
      fill: #64748b !important;
    }
    
    .tap {
      fill: #334155 !important;
      color: #f1f5f9 !important;
    }
    
    .legend {
      font-weight: 500;
    }
  separate_combo_diagrams: true
  shrink_wide_legends: 8.0
  glyph_tap_size: 14.0
  glyph_hold_size: 12.0
  append_colon_to_layer_header: false

parse_config:
  preprocess: true
  sticky_label: "sticky"
  toggle_label: "toggle"
  trans_legend:
    type: "trans"
    align: "center"
  zmk_keycode_map:
    GRAVE: "`"
    TILDE: "~"
    SPACE: "space"
    TAB: "tab"
    RET: "enter" 
    ENTER: "enter"
    ESC: "esc"
    BSPC: "⌫"
    DEL: "del"
    LSHFT: "shift"
    RSHFT: "shift" 
    LCTRL: "ctrl"
    RCTRL: "ctrl"
    LALT: "alt"
    RALT: "alt"
    LGUI: "cmd"
    RGUI: "cmd"
    LEFT_WIN: "win"
    RIGHT_WIN: "win"
    LEFT: "←"
    RIGHT: "→" 
    UP: "↑"
    DOWN: "↓"
    MINUS: "-"
    EQUAL: "="
    PLUS: "+"
    UNDERSCORE: "_"
    PIPE: "|"
    BACKSLASH: "\\"
    NON_US_BACKSLASH: "\\"
    SEMICOLON: ";"
    SQT: "'"
    DOUBLE_QUOTES: "\""
    COMMA: ","
    DOT: "."
    FSLH: "/"
    LBKT: "["
    RBKT: "]"
    PG_UP: "pgup"
    PG_DN: "pgdn"
    HOME: "home"
    END: "end"
    INSERT: "ins"
    PRINTSCREEN: "prt"
    F1: "F1"
    F2: "F2" 
    F3: "F3"
    F4: "F4"
    F5: "F5"
    F6: "F6"
    F7: "F7"
    F8: "F8"
    F9: "F9"
    F10: "F10"
    F11: "F11"
    F12: "F12"
