name: Draw ZMK keymaps
on:
  push:
    paths:
      - "config/*.keymap"
      - "config/*.dtsi"
      - "config/draw_config.yaml"
  workflow_dispatch:

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "config/*.keymap"
      config_path: "config/draw_config.yaml"
      output_folder: "img" 
      parse_args: "--zmk-keymap" 
      draw_args: "--separate-layers"
      commit_message: "keymap-drawer: Update keymap visualizations"
