name: Draw ZMK keymaps
on:
  push:
    paths:
      - "config/*.keymap"
      - "config/*.dtsi"
  workflow_dispatch:

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "config/*.keymap"
      config_path: ""
      output_folder: "img" 
      parse_args: "" 
      draw_args: ""
